name: Build buildenv Docker

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      #-
      #  uses: docker/setup-buildx-action@v1
      #  id: buildx
      #  with:
      #    install: true
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Dockers
        run: cd ./buildenv && bash ./build_docker.sh

